version: '3.8'

services:
        python:
                build: .
                container_name: disaster-tweets
                ports:
                        - "8888:8888"
                        - "9999:9999"
                        - "6006:6006"
                volumes:
                        - type: bind
                          source: .
                          target: /home/jovyan/work

                working_dir: /home/jovyan/work
                environment:
                    - PYTHONPATH=/home/jovyan/work/src